- name: Main playbook
  hosts: localhost
  gather_facts: true
  tasks:
  - name: update apt cache
    community.docker.docker_container_exec:
      container: vhost1
      command: apt-get update

  - name: install wget curl
    community.docker.docker_container_exec:
      container: vhost1
      command: apt-get install -y wget curl unzip
    register: result 

  - name: status of install
    ansible.builtin.debug:
      msg: "{{ result }}"